name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "17.2.0"
      - run: npm install
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          PAGES_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}